name: Trigger auto deployment for collab-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.COLLABSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COLLABSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COLLABSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./server
          dockerfilePath: Dockerfile

          registryUrl: collabe.azurecr.io
          registryUsername: ${{ secrets.COLLABSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COLLABSERVER_REGISTRY_PASSWORD }}

          imageToBuild: collabe.azurecr.io/collab-server:${{ github.sha }}

          containerAppName: collab-server
          resourceGroup: myapp-env
